version: "3"
services:

  # nginx
  # =====
  www:
    container_name: "ldto2022-nginx"
    image: lscr.io/linuxserver/nginx
    restart: unless-stopped
    volumes:
     - "/srv/nginx:/config"
    ports:
     - "80:80"
     - "443:443"
    environment:
     - PUID=1000
     - PGID=1000
     - TZ=Europe/Rome
     
  # mariadb
  # =======
  db:
    image: lscr.io/linuxserver/mariadb
    container_name: "ldto2022-mariadb"
    restart: unless-stopped
    volumes:
     - "/srv/mariadb:/config"
    environment:
     - PUID=1000
     - PGID=1000
     - TZ=Europe/Rome
     - MYSQL_ROOT_PASSWORD=ldto2022
     - MYSQL_DATABASE=nextcloud
     - MYSQL_USER=nextcloud
     - MYSQL_PASSWORD=ldto2022

  # Nextcloud
  # =========
  cloud:
    container_name: "ldto2022-nextcloud"
    restart: unless-stopped
    image: nextcloud:25-apache
    volumes:
      - "/srv/nextcloud/data:/var/www/html/data"
      - "/srv/nextcloud/config:/var/www/html/config"
      - "/srv/nextcloud/apps:/var/www/html/custom_apps"
      - "/srv/nextcloud/nextcloud.log:/var/www/html/data/nextcloud.log"
    ports:
     - "8080:80"
     - "8443:443"
    environment:
      MYSQL_HOST: ldto2022-mariadb
